global:
    smtp_from: 'davontur@gmail.com'
    smtp_smarthost: 'smtp.gmail.com:587'
    smtp_auth_username: 'davontur@gmail.com'
    smtp_auth_identity: 'davontur@gmail.com'
    smtp_auth_password: 'B0uleVard!73'

route:
  receiver: admin
  routes:
  - match_re:
      app_type: linux
    receiver: ss-admin
    routes:
    - match:
        severity: critical
      receiver: linux-team-manager
    - match:
        severity: warning
      receiver: linux-team-lead
        

receivers:
- name: admin
  email_configs:
  - to: 'btc.sent@gmail.com'

- name: ss-admin
  email_configs:
  - to: 'bob.sent@ziggo.nl'

- name: linux-team-manager
  email_configs:
  - to: 'btc.sent@gmail.com'

- name: linux-team-lead
  email_configs:
  - to: 'bob.sent@ziggo.nl'
